---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "RealIT Solutions WA"
keywords:    "RealIT, Solutions, 3D Printing, IT, Prototype, 3D print, Western Australia, WA"
description: "RealIT Solutions is a company based on meeting your DIY technological needs."
source_link: "http://realitsolutions.com.au/"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-178433444-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#00cfff'
  green:     '#56f600'
  purple:    '#ff00a4'
  orange:    '#ffc200'
  gray: '#d3d3d3'

kramdown:
  auto_ids:  false

